site_name: Cockpitdecks Documentation

site_url: https://devleaks.github.io/cockpitdecks-docs/
repo_url: https://github.com/devleaks/cockpitdecks
site_description: Documentation for Cockpitdecks X-Plane Application and Plugin
copyright: |
  Copyright &copy; 2023 - 2024 <a href="https://github.com/devleaks"  target="_blank" rel="noopener">Pierre M</a>

theme:
  name: material # Must use Material theme
  custom_dir: docs/.theme # If you have overrides, specify where to find them
  icon:
    logo: material/airplane
  palette:
    scheme: dracula # This is how to enables the Dracula theme for dark. For light, it will use default Material with some tweaks.
    primary: deep purple # Primary colors
    accent: orange # accent color
  font:
    text: Roboto
    code: Fira Mono
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotations
  pymdownx:
    sponsor: "https://github.com/sponsors/facelessuser"
#
# Dracula is a dark theme only. Dracula can't stand the light.
#
# ###############################################
#
# Navigation, headings
#
nav:
  - Home:
      - Cockpitdecks: index.md
  - Cockpitdecks:
      - Cockpit: Cockpit.md
      - Deck: Deck.md
      - Layout: Layout.md
      - Page: Page.md
      - Button: Button.md
      - Buttons:
          - Button Index: Button/Button Index.md
          - Button Activation: Button/Button Activation.md
          - Button Representation:
              - Button Representation: Button/Button Representation.md
              - Basic Buttons: Button/Button Representations/Basic.md
              - Drawn Buttons: Button/Button Representations/Drawn Buttons.md
              - Annunciators: Button/Button Representations/Annunciator.md
              - Switches: Button/Button Representations/Drawn Buttons – Switches.md
              - Charts Buttons: Button/Button Representations/Drawn Buttons – Charts.md
              - Advanced Representations:
                  - Mosaic (Large LCD Touchscreen): Button/Button Representations/Multi-Buttons and Mosaic.md
                  - Deck Specific Representations – Stream Deck: Button/Button Representations/Deck Specific – Stream Deck.md
                  - Deck Specific Representations – Loupedeck: Button/Button Representations/Deck Specific – Loupedeck.md
                  - Deck Specific Representations – X-Touch Mini: Button/Button Representations/Deck Specific – X-Touch Mini.md
                  - Aircraft Specific Representations – Toliss Airbus: Button/Button Representations/Toliss Specific Representations.md
                  - Weather Representations: Button/Button Representations/Weather.md
                  - Animated Buttons: Button/Button Representations/Animations.md
          - Button Attributes: Button/Button Attribute Default Values.md
          - Button Value: Button/Button Value.md
      - Resources: Resources.md
      - Examples: Extending/Examples.md
      - Extending:
          - Extending Cockpitdecks: Extending/Extending Cockpitdecks.md
          - Adding representations: Extending/Adding Representations.md
          - Adding activations: Extending/Adding Activations.md
          - Activation for developers: Extending/Button Activations for Developers.md
          - Adding web decks: Extending/Web Decks.md
          - Workflow for Web Deck Design: Extending/Internals/Workflow for Web Deck Design.md
          - Adding new physical deck models: Extending/Adding New Deck Models.md
          - Cockpitdecks Internals:
              - History: History.md
              - Simulator:
                  - Simulator: Extending/Simulator.md
                  - X-Plane Plugin: Extending/Complement Plugin - Continuous Commands.md
                  - X-Plane Interaction: Extending/Internals/X-Plane Interaction.md
              - Cockpitdecks Internals: Extending/Internals/Cockpitdecks Internals.md
              - Deck Internals: Extending/Internals/Deck Internals.md
              - Events: Extending/Internals/Events.md
              - String Datarefs: Extending/String Datarefs.md
              - Web Deck Designer Tools: Extending/Internals/Design Helper.md
              - Configuration Files and Attributes: Extending/Internals/Configuration Files and Attributes.md
              - Themes: Extending/Internals/Themes.md
              - To Do: Extending/Internals/To do.md
  - Installation and Usage:
      - Installation: Installation.md
      - Usage: Usage.md

# ###############################################
#
# Plugins
#
plugins:
  - search
  - roamlinks
  - callouts
  - charts
  - tags
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
  - git-revision-date-localized:
      fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          # options:
          #   show_source: false

# ###############################################
#
# Extensions
#
# Note: Some extensions have been commented out because unused.
#       Restoring some extension may require added appropriate
#       python package.
#
markdown_extensions:
  - nl2br
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - pymdownx.keys
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        # Please recall that fence must match Obsidian mermaid plugin
        - name: mermaid
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
            # - name: math
            #   class: arithmatex
            #   format:
            #     !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format { kwds: { mode: generic, tag: pre } }
            # - name: md-render
            #   class: md-render
            #   format: !!python/name:tools.pymdownx_md_render.md_sub_render

            # Vega Lite charts
            #
            # Please recall that fence must match Vega/Vega-Lite Obsidian
            # plugin https://github.com/Justin-J-K/obsidian-vega
            # (In above Obsidian plugin, fences cannot be changed.)


        - name: vega-lite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite # Vega-Lite charts


        - name: vega
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite # Vega charts


  - pymdownx.highlight:
      extend_pygments_lang:
        - name: js
          lang: js
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format { kwds: { mode: generic } }
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  # - pymdownx.arithmatex:
  #     generic: true
  #     block_tag: "pre"
  - pymdownx.mark:
  - pymdownx.striphtml:
  # - pymdownx.snippets:
  #     base_path:
  #       - docs/src/markdown/.snippets
  #       - LICENSE.md
  #       - SECURITY.md
  #     auto_append:
  #       - refs.md
  #     check_paths: true
  # - pymdownx.keys:
  #     separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders:
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
      types:
        - name: details-new
          class: new
        - name: details-settings
          class: settings
        - name: details-note
          class: note
        - name: details-abstract
          class: abstract
        - name: details-info
          class: info
        - name: details-tip
          class: tip
        - name: details-success
          class: success
        - name: details-question
          class: question
        - name: details-warning
          class: warning
        - name: details-failure
          class: failure
        - name: details-danger
          class: danger
        - name: details-bug
          class: bug
        - name: details-example
          class: example
        - name: details-quote
          class: quote
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  # - tools.collapse_code:
  #     expand_text: ""
  #     collapse_text: ""

# ###############################################
#
# Extras
#
extra_javascript:
  - assets/js/extra-loader.js
  - assets/js/material-extra-3rdparty.js
  - assets/js/material-extra-theme.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra_css:
  - assets/css/extra.css
  - assets/css/fonts.css
  - assets/css/dracula-colors.css
