nav:

  - Welcome: index.md

  - Getting started: Design/Deck Design.md

  - Installation/Installation.md

  - Usage:
      - Demonstration web deck: Design/Demonstration Web Deck.md
      - Installing a new deck: Design/Deck Design.md
      - Defining buttons: Design/Adding a Page of Buttons to a Deck.md
      - Web decks: Web Decks.md

  - Extensions:
      - Extensions/About Extensions.md
      - Simulators:
        - Laminar Research X-Plane:
          - Extensions/Simulators/X-Plane/Laminar Research X-Plane.md
          - Extensions/Simulators/X-Plane/X-Plane Observables.md
      - Decks:
        - Extensions/Decks/Elgato.md
        - Extensions/Decks/Loupedeck.md
        - Berhinger X-Touch Mini: Extensions/Decks/Berhinger.md
      - Others:
        - Extensions/Others/Weather.md
        - Extensions/Others/ToLiss Airbus Aircrafts.md

  - Reference:
      - Buttons:
        - Reference/Button.md
        - Value: Reference/Button Value.md
        - Attribute Default Values: Reference/Button Attribute Default Values.md
        - Reference/Activations.md
        - Reference/Representations.md
      - Reference/Page.md
      - Reference/Layout.md
      - Reference/Resources.md
      - Reference/Deck.md
      - Reference/Observables.md
      - Reference/deckconfig Folder.md
      - Reference/Activations.md
      - Reference/Representations.md

  - Development:
      - Reference/Extending/Extending Cockpitdecks.md
      - Creating your extensions:
        - "Reference/Extending/Development/*.md"
      - Core Entities:
        - Reference/Simulator.md
        - Reference/Cockpit.md
        - Reference/Extending/Development/Internals/Events.md
      - Internals:
        - "Reference/Extending/Development/Internals/*.md"
      - Python API for core entities:
        - "Reference/Extending/Development/API/*.md"

  - About:
     - History of Cockpitdecks: About/History.md
     - Glossary of Cockpitdecks Terms: Reference/Glossary.md
